Namzadan/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

admin.autodiscover()
urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mainapp.urls')),
                  path('summernote/', include('django_summernote.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

mainapp/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name="home"),
    path('contact-us/', contact_us, name="contact_us"),
    path('candidates/', home, name="candidates"),
    path('resume/<int:pk>', resume, name="resume"),
    path('get_cities/', get_cities, name="get_cities"),

]

mainapp/models.py
from django.db import models
from django.urls import reverse
from django.utils.html import format_html
from django.utils.text import Truncator
from django.utils.html import strip_tags


class Province(models.Model):
    name = models.CharField(max_length=50, verbose_name="نام استان", unique=True)

    class Meta:
        verbose_name = "استان"
        verbose_name_plural = "استان‌ها"

    def __str__(self):
        return self.name

    def get_city_count(self):
        return self.city_set.count()

    get_city_count.short_description = "تعداد شهرها"


class City(models.Model):
    province = models.ForeignKey(Province, on_delete=models.CASCADE, verbose_name="استان مربوطه")
    name = models.CharField(max_length=50, unique=True, verbose_name="نام شهر")

    class Meta:
        verbose_name = "شهر"
        verbose_name_plural = "شهرها"

    def __str__(self):
        return self.name + " - " + self.province.name


class Candidate(models.Model):
    OSOOLGARA = 'OS'
    ESLAHTALAB = 'ES'
    OTHER = 'OT'
    UNKNOWN = 'UN'
    PARTIES = [
        (OSOOLGARA, 'اصولگرا'),
        (ESLAHTALAB, 'اصلاح طلب'),
        (OTHER, 'سایر'),
        (UNKNOWN, 'نامشخص'),
    ]

    profile_picture_url = models.ImageField(upload_to='images', default="images/default.png",
                                            blank=True, null=True,
                                            verbose_name="عکس پروفایل")  # 120*162px
    full_name = models.CharField(max_length=50, verbose_name="نام و نام خانوادگی")
    nickname = models.CharField(max_length=50, blank=True, verbose_name="نام مستعار(مشهور به)")
    father_name = models.CharField(max_length=50, verbose_name="نام پدر", blank=True, null=True)
    code = models.CharField(max_length=10, verbose_name="کد انتخاباتی", blank=True, null=True)
    motto = models.TextField(blank=True, verbose_name="شعار انتخاباتی")
    party = models.CharField(max_length=25, choices=PARTIES, default=UNKNOWN, verbose_name="حزب")
    city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name="ناحیه انتخاباتی", default=None)

    def get_profile_picture(self):
        return format_html(
            "<a target='_blank' href='{}'><img width=100 height=75 style='border-radius: 5px;' src='{}'></a>".format(
                self.profile_picture_url.url, self.profile_picture_url.url))

    get_profile_picture.short_description = "عکس"

    def get_resume(self):
        if self.resume:
            return format_html(
                "<a href='{}'>مشاهده</a>".format(reverse('admin:mainapp_resume_change', args=(self.resume.id,)))
            )

    get_resume.short_description = "رزومه"

    class Meta:
        verbose_name = "نامزد"
        verbose_name_plural = "نامزدها"

    def __str__(self):
        return self.full_name

    def save(self, *args, **kwargs):
        if not self.profile_picture_url or self.profile_picture_url is None:
            self.profile_picture_url = "media/images/default.png"
        super().save()


class Resume(models.Model):
    SIKL = 'SI'
    DIPLOM = 'DI'
    FOQEDIPLOM = 'FD'
    LISANS = 'LI'
    FOQELISANS = 'FL'
    DOCTOR = 'DO'
    FOQEDOCTOR = 'FDD'
    HOZAVI = 'HO'
    UNKNOWN = 'UN'
    DEGREES = [
        (SIKL, 'سیکل'),
        (DIPLOM, 'دیپلم'),
        (FOQEDIPLOM, 'فوق دیپلم'),
        (LISANS, 'لیسانس'),
        (FOQELISANS, 'فوق لیسانس'),
        (DOCTOR, 'دکتری'),
        (FOQEDOCTOR, 'فوق دکتری'),
        (HOZAVI, 'حوزوی'),
        (UNKNOWN, 'نامشخص'),
    ]
    candidate = models.OneToOneField(Candidate, on_delete=models.CASCADE, verbose_name="نامزد")
    age = models.IntegerField(blank=True, null=True, verbose_name="سن")
    degree = models.CharField(max_length=50, blank=True, choices=DEGREES, default=UNKNOWN, verbose_name="مدرک تحصیلی")
    field = models.CharField(max_length=50, blank=True, verbose_name="رشته تحصیلی")
    moarefi_barnameha = models.TextField(blank=True, verbose_name="معرفی برنامه ها")
    records = models.TextField(blank=True, verbose_name="سوابق")
    banner1 = models.ImageField(upload_to="banners", default="banners/default.jpg", blank=True,
                                verbose_name="پوستر۱")  # 240*320
    banner2 = models.ImageField(upload_to="banners", default="banners/default.jpg", blank=True, verbose_name="پوستر۲")
    banner3 = models.ImageField(upload_to="banners", default="banners/default.jpg", blank=True, verbose_name="پوستر۳")
    banner4 = models.ImageField(upload_to="banners", default="banners/default.jpg", blank=True, verbose_name="پوستر۴")

    class Meta:
        verbose_name = "رزومه"
        verbose_name_plural = "رزومه‌ها"

    def __str__(self):
        return self.candidate.full_name

    def get_truncated_moarefi_barnameha(self):
        stripped = strip_tags(self.moarefi_barnameha)
        return Truncator(stripped).words(15)

    get_truncated_moarefi_barnameha.short_description = "معرفی برنامه‌ها"


class GlobalAds(models.Model):
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, verbose_name="نامزد", blank=True, null=True)
    banner = models.ImageField(upload_to="global", default="global/default.jpg", blank=True, verbose_name="پوستر")

    class Meta:
        verbose_name = "تبلیغ سراسری"
        verbose_name_plural = "تبلیغات سراسری"

    def save(self, *args, **kwargs):
        if self.banner is None:
            self.banner = "media/global/default.jpg"
        super().save()

    def __str__(self):
        if self.candidate:
            return self.candidate.full_name
        else:
            return super(GlobalAds, self).__str__()

    def get_banner_thumb(self):
        return format_html(
            "<a target='_blank' href='{}'><img width=100 height=75 style='border-radius: 5px;' src='{}'></a>".format(
                self.banner.url, self.banner.url))
    get_banner_thumb.short_description = "بنر تبلیغاتی (برای مشاهده در سایز اصلی،کلیک کنید)"

mainapp/views.py
from django.contrib import messages
from django.core import serializers
from django.shortcuts import render, redirect
from django.db.models import Q
from django.core.paginator import Paginator
from Namzadan import settings

from .models import Candidate, City, Resume, Province, GlobalAds


def home(request):
    all_provinces = Province.objects.all().order_by('name')
    all_zones = City.objects.all().order_by('name')
    global_ads = GlobalAds.objects.all()[:4]
    MEDIA_URL = settings.MEDIA_URL
    if request.method == 'GET':
        selected_province = Province.objects.get(name__exact="تهران")
        selected_zone = City.objects.get(name__exact="تهران، ري، شميرانات، اسلامشهر و پرديس")
        all_candidates = Candidate.objects.filter(city__province=selected_province, city=selected_zone).order_by(
            'resume', 'full_name').reverse()

        paginator = Paginator(all_candidates, 90)
        page_number = 1
        try:
            page_number = request.POST['page']
        except:
            pass
        page_obj = paginator.get_page(page_number)
        return render(request, 'mainapp/all-candidates.html',
                      {'all_candidates': all_candidates, 'all_provinces': all_provinces, 'all_zones': all_zones,
                       'page_obj': page_obj, 'MEDIA_URL': MEDIA_URL, 'selected_province': selected_province,
                       'selected_zone': selected_zone,
                       'global_ads': global_ads})
    else:
        if 'search' in request.POST:
            search_text = str(request.POST['search'])
            all_candidates = Candidate.objects.filter(
                Q(full_name__contains=search_text) | Q(nickname__contains=search_text) | Q(
                    code__contains=search_text)).order_by(
                'resume', 'full_name').reverse()
            if all_candidates.count() == 0:
                messages.error(request, "نتیجه ای یافت نشد")
                return redirect('home')
            paginator = Paginator(all_candidates, 90)
            page_number = 1
            try:
                page_number = request.POST['page']
            except:
                pass
            page_obj = paginator.get_page(page_number)
            return render(request, 'mainapp/all-candidates.html',
                          {'all_candidates': all_candidates, 'all_provinces': all_provinces, 'all_zones': all_zones,
                           'MEDIA_URL': MEDIA_URL,
                           'page_obj': page_obj,
                           'global_ads': global_ads})
        province_pk = request.POST['province']
        zone_pk = request.POST['zone']
        if province_pk == "none":
            if zone_pk == "none":
                selected_province = Province.objects.get(name__exact="تهران")
                selected_zone = City.objects.get(name__exact="تهران، ري، شميرانات، اسلامشهر و پرديس")
                all_candidates = Candidate.objects.filter(city__province=selected_province,
                                                          city=selected_zone).order_by(
                    'resume', 'full_name').reverse()
                paginator = Paginator(all_candidates, 90)
                page_number = 1
                try:
                    page_number = request.POST['page']
                except:
                    pass
                page_obj = paginator.get_page(page_number)
                return render(request, 'mainapp/all-candidates.html',
                              {'all_candidates': all_candidates, 'all_provinces': all_provinces, 'all_zones': all_zones,
                               'MEDIA_URL': MEDIA_URL, 'selected_province': selected_province,
                               'selected_zone': selected_zone,
                               'page_obj': page_obj,
                               'global_ads': global_ads})
        if province_pk == "none":
            if zone_pk != "none":
                all_candidates = Candidate.objects.filter(city_id=zone_pk).order_by(
                    'resume', 'full_name').reverse()
                selected_zone = City.objects.get(pk=zone_pk)
                paginator = Paginator(all_candidates, 90)
                page_number = 1
                try:
                    page_number = request.POST['page']
                except:
                    pass
                page_obj = paginator.get_page(page_number)
                return render(request, 'mainapp/all-candidates.html',
                              {'all_candidates': all_candidates, 'all_provinces': all_provinces, 'all_zones': all_zones,
                               'MEDIA_URL': MEDIA_URL,
                               'page_obj': page_obj, 'selected_zone': selected_zone,
                               'global_ads': global_ads})
        if province_pk != "none":
            if zone_pk == "none":
                selected_province = Province.objects.get(pk=province_pk)
                selected_zone = City.objects.filter(province_id=province_pk).order_by('name').first()
                all_candidates = Candidate.objects.filter(city__province=selected_province,
                                                          city=selected_zone).order_by('resume', 'full_name').reverse()
                paginator = Paginator(all_candidates, 90)
                page_number = 1
                try:
                    page_number = request.POST['page']
                except:
                    pass
                page_obj = paginator.get_page(page_number)
                return render(request, 'mainapp/all-candidates.html',
                              {'all_candidates': all_candidates, 'all_provinces': all_provinces, 'all_zones': all_zones,
                               'MEDIA_URL': MEDIA_URL,
                               'page_obj': page_obj, 'selected_province': selected_province,
                               'selected_zone': selected_zone,
                               'global_ads': global_ads})
        if province_pk != "none":
            if zone_pk != "none":
                all_candidates = Candidate.objects.filter(city__province_id=province_pk, city_id=zone_pk).order_by(
                    'resume', 'full_name').reverse()
                selected_province = Province.objects.get(pk=province_pk)
                selected_zone = City.objects.get(pk=zone_pk)
                paginator = Paginator(all_candidates, 90)
                page_number = 1
                try:
                    page_number = request.POST['page']
                except:
                    pass
                page_obj = paginator.get_page(page_number)
                return render(request, 'mainapp/all-candidates.html',
                              {'all_candidates': all_candidates, 'all_provinces': all_provinces, 'all_zones': all_zones,
                               'MEDIA_URL': MEDIA_URL,
                               'page_obj': page_obj, 'selected_province': selected_province,
                               'selected_zone': selected_zone,
                               'global_ads': global_ads})


def contact_us(request):
    return render(request, 'mainapp/AboutUs.html')


def resume(request, pk):
    MEDIA_URL = settings.MEDIA_URL
    try:
        resume = Resume.objects.get(candidate_id=pk)
    except:
        resume = None
    if resume is None:
        messages.error(request, "رزومه ای برای کاندیدای مورد نظر یافت نشد")
        return redirect('home')
    return render(request, 'mainapp/resume.html', {'resume': resume, 'MEDIA_URL': MEDIA_URL})


def get_cities(request):
    province_id = int(request.GET.get('province_id', None))
    cities = City.objects.filter(province_id=province_id).order_by('name')

    city_json = serializers.serialize('json', cities, fields=('name', 'pk'))

    data = {
        'city_json': city_json,
        'status': 200
    }
    from django.http import JsonResponse
    return JsonResponse(data)

mainapp/templates/mainapp/AboutUs.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <link href="https://netdna.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,900,900i" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'mainapp/css/style.css' %}">
    <title>معرفی نامزدهای انتخابات یازدهمین دوره مجلس شورای اسلامی</title>
</head>

<body>
<a id="button"></a>
<div class="desc-title">
        <span>
            <p class="textnav left-motto">انتخاب آگاهانه</p>
            <p class="textnav middle-motto">حفظ زیبایی</p>
            <p class="textnav right-motto">تبلیغات ماندگار</p>
        </span>
    <span class="slugan">معرفی نامزدهای انتخابات یازدهمین دوره مجلس شورای اسلامی</span>

</div>
<nav class="navbar navbar-expand-lg navigationbar sticky-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30" role="img" focusable="false">
            <title>Menu</title>
            <path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2"
                  d="M4 7h22M4 15h22M4 23h22"></path>
        </svg>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">مشاهده نامزدها</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'contact_us' %}">تماس با ما</a>
            </li>

        </ul>
    </div>
    <div>
        <form class="form-inline" method="post" action="{% url 'home' %}">
            {% csrf_token %}
            <input name="search" class="search-input form-control mr-sm-2" type="search"
                   placeholder="قسمتی از کد یا نام نامزد را بنویسید" aria-label="Search">
            <button class="btn btn-outline-dark my-2 my-sm-0 Searchbutton" type="submit"><i class="fa fa-search"></i></button>
        </form>
    </div>
</nav>

<div class="container main-aboutus">
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h3 class="Aboutustitle">درباره نامزدان</h3>
            <p class="Aboutustext">
            <p style="direction: rtl;">سایت نامزدان با هدف معرفی برنامه ها و سوابق نامزدهای انتخابات یازدهمین دوره مجلس
                شورای اسلامی راه اندازی گردیده است تا هم به مردم در انتخاب آگاهانه کمک نماید و هم انجام تبلیغات برای
                نامزدهای محترم نمایندگی را تسهیل و کم هزینه نماید.</p>
            <p style="direction: rtl;">معرفی کاندیداها و برنامه ها و سوابق آنها در این سایت، بر خلاف تبلیغات با استفاده
                از کاغذ و بنر، ماندگار است و به حفظ زیبایی شهرها کمک می نماید.</p>
            <p style="direction: rtl;">مشخصات فردی نامزدهای انتخابات که در این سایت ارائه گردیده است، بر گرفته از آگهی
                های انتخابات رسمی منتشر شده توسط فرمانداری ها می باشد.</p>
            <p style="direction: rtl;">سوابق درج شده برای هر نامزد براساس محتوای ارسال شده توسط نامزدهای انتخابات به این
                سایت است و این سایت مسئولیتی در خصوص صحت این سوابق ندارد.</p>
            <p style="direction: rtl;">کلیه حقوق مادی و معنوی این سایت متعلق به شرکت ایده پردازان رایان نیرو می
                باشد.</p>
        </div>
    </div>
</div>
<div class="container main-aboutus">
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h3 class="Aboutustitle">روش ارسال سوابق و برنامه ها توسط نامزدها </h3>
            <p class="Aboutustext">
            <p style="direction: rtl;">
                نامزدهای محترم می توانند جهت درج سوابق، برنامه ها و پوستر تبلیغاتی خود (در ابعاد ۳۵۰×۳۱۰ پیکسل) در صفحه
                اختصاصی شان در این سایت، موارد زیر را به آیدی@namzadan98 یا شماره ۰۹۰۵۵۱۵۱۷۳۰ در پیام رسان تلگرام یا
                واتساپ ارسال کنند یا به ایمیلnamzadan98@gmail.com ارسال نمایند.</p>
            <p style="direction: rtl;">۱- مشخصات، برنامه ها و سوابق نامزد شامل:</p>
            <p style="text-indent: 50px;">
            <p style="direction: rtl;"> *نام و نام خانوادگی</p>
            <p style="direction: rtl;"> نام پدر</p>
            <p style="direction: rtl;"> کد نامزد</p>
            <p style="direction: rtl;"> *استان و حوزه انتخاباتی</p>
            <p style="direction: rtl;"> مدرک و رشته تحصیلی</p>
            <p style="direction: rtl;"> سن</p>
            <p style="direction: rtl;"> شعار انتخاباتی</p>
            <p style="direction: rtl;"> گرایش سیاسی</p>
            <p style="direction: rtl;"> لیست برنامه&zwnj;ها</p>
            <p style="direction: rtl;"> لیست سوابق</p>
            <p style="direction: rtl;"> (تنها درج موارد ستاره&zwnj;دار الزامی است)</p>

            <p style="direction: rtl;">۲-
                فایل پوستر تبلیغاتی نامزد</p>
            <p style="direction: rtl;">۳- تصویر واریز هزینه به صورت کارت به کارت به شماره کارت بانکی ۶۰۳۷۹۹۷۱۲۶۸۸۵۱۲۹
                بانک ملی ایران به نام خانم مریم اکملی</p>

            <p style="direction: rtl;">محتوای درج شده در صفحه اختصاصی هر نامزد، تا روز برگزاری انتخابات باقی خواهد
                ماند.</p>
            <p style="text-align: right;">&nbsp; --------------------------</p>


            <p style="direction: rtl;">
                نامزدهای محترم یا گروه های سیاسی می توانند فایل پوستر تبلیغاتی خود را جهت درج در بالا یا پایین صفحه اصلی
                سایت (در ابعاد ۳۲۰×۲۴۰ پیکسل) به همراه تصویر واریز هزینه به شماره کارت بانکی فوق، به آیدی@namzadan98 یا
                شماره ۰۹۰۵۵۱۵۱۷۳۰ در پیام رسان تلگرام یا واتساپ ارسال کنند یا به ایمیلnamzadan98@gmail.com ارسال نمایند.
            </p>
            <p style="direction: rtl;">هزینه درج پوستر تبلیغاتی در بالای صفحه اصلی سایت برای هر روز ۱۵۰۰۰۰ تومان و در
                پایین صفحه اصلی سایت برای هر روز ۸۰۰۰۰ تومان می&zwnj;باشد.</p>
            <p style="text-align: right;">&nbsp; --------------------------</p>
            <p style="direction: rtl;">شماره تماس جهت کسب اطلاعات بیشتر: ۰۹۰۵۵۱۵۱۷۳۰</p>
        </div>
    </div>
</div>


<script src="https://netdna.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script>
    var btn = $('#button');

    $(window).scroll(function () {
        if ($(window).scrollTop() > 300) {
            btn.addClass('show');
        } else {
            btn.removeClass('show');
        }
    });

    btn.on('click', function (e) {
        e.preventDefault();
        $('html, body').animate({scrollTop: 0}, '300');
    });
</script>
<footer>
    <div class="alert alert-dark" role="alert">
        کلیه حقوق مادی و معنوی این سایت متعلق به شرکت ایده پردازان رایان نیرو می باشد
    </div>
</footer>
</body>

</html>

mainapp/templates/mainapp/resume.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <link href="https://netdna.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,900,900i" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'mainapp/css/style.css' %}">
    <title>صفحه ی مشخصات {{ resume.candidate.full_name }}</title>

</head>

<body>
<a id="button"></a>
<div class="desc-title">
        <span>
            <p class="textnav left-motto">انتخاب آگاهانه</p>
            <p class="textnav middle-motto">حفظ زیبایی</p>
            <p class="textnav right-motto">تبلیغات ماندگار</p>
        </span>
    <span class="slugan">معرفی نامزدهای انتخابات یازدهمین دوره مجلس شورای اسلامی</span>

</div>
<nav class="navbar navbar-expand-lg navigationbar sticky-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30" role="img" focusable="false">
            <title>Menu</title>
            <path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2"
                  d="M4 7h22M4 15h22M4 23h22"></path>
        </svg>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">مشاهده نامزدها</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'contact_us' %}">تماس با ما</a>
            </li>

        </ul>
    </div>
    <div>
        <form class="form-inline" method="post" action="{% url 'home' %}">
            {% csrf_token %}
            <input name="search" class="search-input form-control mr-sm-2" type="search"
                   placeholder="قسمتی از کد یا نام نامزد را بنویسید" aria-label="Search">
            <button class="btn btn-outline-dark my-2 my-sm-0 Searchbutton" type="submit"><i class="fa fa-search"></i></button>
        </form>
    </div>
</nav>
<div class="">


    <div class="Main-content">
        <div class="left-sidebar">
            <img class="side-posters" src="{{ MEDIA_URL }}{{ resume.banner1 }}" alt="بنر۱">
            <img class="side-posters" src="{{ MEDIA_URL }}{{ resume.banner2 }}" alt="بنر۲">
            <img class="side-posters" src="{{ MEDIA_URL }}{{ resume.banner3 }}" alt="بنر۳">
            <img class="side-posters" src="{{ MEDIA_URL }}{{ resume.banner4 }}" alt="بنر۴">

        </div>
        <div class="user-info">
            <div class="profile-picture">
                <img src="{{ MEDIA_URL }}{{ resume.candidate.profile_picture_url }}" alt="" height="300" width="230">
            </div>
            <div class="basic-info">
                <ul class="list-group">
                    <li class="list-group-item"><label for="">نام و نام خانوادگی
                        : {{ resume.candidate.full_name }}</label>
                    </li>
                    {% if resume.candidate.father_name %}
                        <li class="list-group-item">فرزند {{ resume.candidate.father_name }}</li>
                    {% endif %} {% if resume.candidate.nickname %}
                    <li class="list-group-item">مشهور به {{ resume.candidate.nickname }}</li>
                {% endif %} {% if resume.candidate.code %}
                    <li class="list-group-item">کد نامزد: {{ resume.candidate.code }}</li>
                {% endif %}
                    <li class="list-group-item">حوزه انتخابیه: {{ resume.candidate.city.name }} </li>
                    <!-- <li class="list-group-item">محل تولد : {{ resume.birth_locate }}</li> -->
                    <!-- <li class="list-group-item">رشته تحصیلی : {{ resume.field }}</li> -->
                    {% if resume.age %}
                        <li class="list-group-item" style="direction: rtl;">سن : {{ resume.age }} سال</li>
                    {% endif %}
                    {% if resume.field %}{% if resume.degree %}
                        <li class="list-group-item">مدرک و رشته تحصیلی
                            : {{ resume.get_degree_display }} {{ resume.field }}</li>
                    {% endif %} {% endif %}
                    {% if resume.candidate.motto %}
                        <li class="list-group-item">شعار انتخاباتی : {{ resume.candidate.motto | safe }} </li>
                    {% endif %}
                    <li class="list-group-item">گرایش سیاسی : {{ resume.candidate.get_party_display }}</li>
                </ul>
                <div class="jumbotron Past-Activities ">
                    <ul class="list-unstyled">
                        <li class="media">
                            <div class="media-body">
                                <h5 class="mt-0 mb-1 Resumetitle">- معرفی برنامه ها</h5>
                                {% if not resume.moarefi_barnameha %}
                                    اطلاعاتی وارد نشده است
                                {% else %}
                                    {{ resume.moarefi_barnameha | safe }}
                                {% endif %}

                                <h5 class="mt-0 mb-1 biographytitle"> - سوابق مدیریتی</h5>
                                {% if not resume.records %}
                                    اطلاعاتی وارد نشده است
                                {% else %}
                                    {{ resume.records | safe }}
                                {% endif %}

                            </div>
                        </li>
                    </ul>
                </div>

            </div>

        </div>
        <div class="right-sidebar">
            <img class="side-posters" src="{{ MEDIA_URL }}{{ resume.banner1 }}" alt="بنر۱">
            <img class="side-posters" src="{{ MEDIA_URL }}{{ resume.banner2 }}" alt="بنر۲">
            <img class="side-posters" src="{{ MEDIA_URL }}{{ resume.banner3 }}" alt="بنر۳">
            <img class="side-posters" src="{{ MEDIA_URL }}{{ resume.banner4 }}" alt="بنر۴">
        </div>
    </div>
</div>

<script src="https://netdna.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script>
    var btn = $('#button');

    $(window).scroll(function () {
        if ($(window).scrollTop() > 300) {
            btn.addClass('show');
        } else {
            btn.removeClass('show');
        }
    });

    btn.on('click', function (e) {
        e.preventDefault();
        $('html, body').animate({scrollTop: 0}, '300');
    });
</script>
<footer>
    <div class="alert alert-dark" role="alert">
        کلیه حقوق مادی و معنوی این سایت متعلق به شرکت ایده پردازان رایان نیرو می باشد
    </div>
</footer>

</body>

</html>